import os
import time
import random
from typing import Dict, Any, List, Optional
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

app = FastAPI(title="Full-Stack Coding & Architecture Agent", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

tasks_db: Dict[str, Dict[str, Any]] = {}

class QuoteRequest(BaseModel):
    taskId: str
    taskType: str
    description: str
    prompt: Optional[str] = None
    estimatedComplexity: Optional[str] = "MEDIUM"

class QuoteResponse(BaseModel):
    agentId: str = "agent-code-02"
    agentName: str = "Full-Stack Coding & Architecture Agent"
    price: float
    estimatedTime: int
    confidence: float
    successRate: float
    rating: float
    supportedCapabilities: List[str]

class ExecuteRequest(BaseModel):
    taskId: str
    taskType: str
    description: str
    prompt: Optional[str] = None
    inputContext: Optional[Dict[str, Any]] = None

@app.get("/health")
def health_check():
    return {
        "status": "UP",
        "agentId": "agent-code-02",
        "agentName": "Full-Stack Coding & Architecture Agent",
        "service": "CodingAgentService",
        "uptimeSeconds": 3600
    }

@app.post("/quote", response_model=QuoteResponse)
def get_quote(request: QuoteRequest):
    complexity_multiplier = 1.0
    if request.estimatedComplexity == "HIGH":
        complexity_multiplier = 1.5
    elif request.estimatedComplexity == "LOW":
        complexity_multiplier = 0.75

    base_price = 80.0 * complexity_multiplier
    estimated_time = int(18 * complexity_multiplier)
    
    return QuoteResponse(
        agentId="agent-code-02",
        agentName="Full-Stack Coding & Architecture Agent",
        price=round(base_price + random.uniform(-3, 7), 2),
        estimatedTime=estimated_time,
        confidence=95.0,
        successRate=96.0,
        rating=4.8,
        supportedCapabilities=["FRONTEND", "BACKEND", "DEVELOPMENT", "REACT", "SPRING_BOOT", "API_DESIGN"]
    )

@app.post("/execute")
def execute_task(request: ExecuteRequest):
    task_id = request.taskId
    tasks_db[task_id] = {"status": "RUNNING", "startTime": time.time(), "output": None}
    
    topic = request.description or request.prompt or "Web App Component"
    
    output_content = (
        f"// ==========================================\n"
        f"// Full-Stack Generated Module: {topic}\n"
        f"// Generated by AgentMesh Code Agent\n"
        f"// ==========================================\n\n"
        f"import React, {{ useState, useEffect }} from 'react';\n"
        f"import {{ Shield, Zap, CheckCircle, ArrowRight }} from 'lucide-react';\n\n"
        f"export const GeneratedComponent = () => {{\n"
        f"  const [loading, setLoading] = useState(false);\n"
        f"  const [txHash, setTxHash] = useState('');\n\n"
        f"  const handleAtomicPayment = async () => {{\n"
        f"    setLoading(true);\n"
        f"    // Simulating Algorand Group Transaction submission\n"
        f"    setTimeout(() => {{\n"
        f"      setTxHash('ALG-TX-' + Math.random().toString(36).substring(2, 12).toUpperCase());\n"
        f"      setLoading(false);\n"
        f"    }}, 1200);\n"
        f"  }};\n\n"
        f"  return (\n"
        f"    <div className=\"p-8 bg-slate-900 border border-cyan-500/30 rounded-2xl shadow-2xl text-white max-w-2xl mx-auto\">\n"
        f"      <div className=\"flex items-center space-x-3 mb-4\">\n"
        f"        <Zap className=\"w-8 h-8 text-cyan-400 animate-pulse\" />\n"
        f"        <h2 className=\"text-2xl font-bold bg-gradient-to-r from-cyan-400 to-indigo-400 bg-clip-text text-transparent\">\n"
        f"          {topic}\n"
        f"        </h2>\n"
        f"      </div>\n"
        f"      <p className=\"text-slate-400 mb-6\">\n"
        f"        Autonomous multi-agent execution connected directly to Algorand Atomic Group Transfers.\n"
        f"      </p>\n"
        f"      <div className=\"grid grid-cols-2 gap-4 mb-6\">\n"
        f"        <div className=\"p-4 bg-slate-800/80 rounded-xl border border-slate-700\">\n"
        f"          <span className=\"text-xs text-slate-400 block\">Status</span>\n"
        f"          <span className=\"text-emerald-400 font-semibold flex items-center gap-1 mt-1\">\n"
        f"            <CheckCircle className=\"w-4 h-4\" /> Production Ready\n"
        f"          </span>\n"
        f"        </div>\n"
        f"        <div className=\"p-4 bg-slate-800/80 rounded-xl border border-slate-700\">\n"
        f"          <span className=\"text-xs text-slate-400 block\">Settlement</span>\n"
        f"          <span className=\"text-cyan-400 font-semibold flex items-center gap-1 mt-1\">\n"
        f"            <Shield className=\"w-4 h-4\" /> Algorand Escrow\n"
        f"          </span>\n"
        f"        </div>\n"
        f"      </div>\n"
        f"      <button \n"
        f"        onClick={{handleAtomicPayment}}\n"
        f"        disabled={{loading}}\n"
        f"        className=\"w-full py-3 bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 rounded-xl font-bold flex items-center justify-center space-x-2 transition-all transform active:scale-95 shadow-lg shadow-cyan-500/20\"\n"
        f"      >\n"
        f"        <span>{{loading ? 'Settling via Algorand...' : 'Execute & Pay Escrow'}}</span>\n"
        f"        <ArrowRight className=\"w-5 h-5\" />\n"
        f"      </button>\n"
        f"      {{txHash && (\n"
        f"        <div className=\"mt-4 p-3 bg-emerald-950/60 border border-emerald-500/40 rounded-lg text-emerald-300 text-xs font-mono break-all text-center\">\n"
        f"          Transaction Verified: {{txHash}}\n"
        f"        </div>\n"
        f"      )}}\n"
        f"    </div>\n"
        f"  );\n"
        f"}};\n"
        f"export default GeneratedComponent;"
    )
    
    tasks_db[task_id] = {"status": "COMPLETED", "completedAt": time.time(), "output": output_content}
    return {"taskId": task_id, "status": "COMPLETED", "agentId": "agent-code-02", "output": output_content}

@app.get("/status/{taskId}")
def get_task_status(taskId: str):
    if taskId not in tasks_db:
        raise HTTPException(status_code=404, detail="Task not found")
    return tasks_db[taskId]

if __name__ == "__main__":
    import uvicorn
    port = int(os.environ.get("PORT", 8002))
    uvicorn.run(app, host="0.0.0.0", port=port)
